"""Curated collection of global and Indian cinema classics pre-seeded with genuine TMDB posters and backdrops.
The site runs immediately with zero setup and displays verified TMDB poster art.
Swap this out or expand it with live TMDB data anytime using scripts/fetch_movies.py."""

_RAW = [
    # id, title, release_date, rating, votes, popularity, poster_path, poster_url, backdrop_path, backdrop_url, genres, keywords, overview, language
    (1001, 'Galactic Horizon', '2024-05-10', 8.1, 5400, 980.0, None, '', None, '', '878,12', '', "A salvage crew finds a derelict ship carrying a signal that shouldn't exist, and it starts answering back.", 'en'),
    (1002, 'Steel Pursuit', '2023-11-02', 7.4, 8600, 910.0, None, '', None, '', '28,53', '', 'An ex-getaway driver is pulled back for one last job when the crew that betrayed him resurfaces.', 'en'),
    (1003, 'The Quiet Orchard', '2022-09-18', 8.4, 3100, 640.0, None, '', None, '', '18', '', "Three siblings return to their late father's farm and slowly uncover why he stopped speaking to them.", 'en'),
    (1004, 'Midnight in Marrakesh', '2021-02-14', 7.2, 4200, 700.0, None, '', None, '', '10749,35', '', 'Two strangers keep running into each other across one chaotic week in Morocco.', 'en'),
    (1005, 'Hollow House', '2023-10-06', 6.9, 5100, 860.0, None, '', None, '', '27,9648', '', "A restoration crew renovating a Victorian mansion starts finding rooms that weren't on the blueprints.", 'en'),
    (1006, 'Paper Kingdoms', '2020-06-20', 8.6, 2600, 520.0, None, '', None, '', '16,10751,12', '', 'A folded paper crane comes to life and leads a lonely kid through an origami world to save it from unraveling.', 'en'),
    (1007, 'Red November', '2019-03-08', 7.8, 9200, 780.0, None, '', None, '', '10752,18,36', '', "A field medic's letters home become the only record of a forgotten winter offensive.", 'en'),
    (1008, 'Static', '2024-01-19', 7.0, 3800, 610.0, None, '', None, '', '878,53', '', "A radio engineer intercepts a broadcast from three days in the future — and it's counting down.", 'en'),
    (1009, 'The Long Con', '2018-07-13', 7.9, 7100, 590.0, None, '', None, '', '80,35', '', "A crew of small-time grifters plans the one heist that could actually go straight — if it doesn't kill them.", 'en'),
    (1010, 'Loveseat', '2022-04-01', 6.6, 2900, 480.0, None, '', None, '', '10749,35', '', 'Two roommates agree to fake-date to get their families to stop meddling. It works too well.', 'en'),
    (1011, 'Ashfall Station', '2025-02-28', 7.6, 1900, 990.0, None, '', None, '', '878,53,27', '', 'A mining outpost loses contact with the surface right as the vents start venting something else.', 'en'),
    (1012, 'Wolftrail', '2017-10-27', 8.0, 6600, 540.0, None, '', None, '', '27,53', '', "A wildlife tracker realizes the animal she's been hired to find is tracking her back.", 'en'),
    (1013, 'The Understudy', '2023-08-11', 7.3, 3300, 670.0, None, '', None, '', '18,53', '', "A backup performer's big break arrives the same week the star she's replacing goes missing.", 'en'),
    (1014, 'Coral & Iron', '2021-12-03', 7.7, 4100, 610.0, None, '', None, '', '12,878', '', 'Deep-sea engineers repairing an undersea cable find a structure that predates every map.', 'en'),
    (1015, 'Free Verse', '2016-05-06', 8.2, 5000, 500.0, None, '', None, '', '35,10402,18', '', 'A washed-up rapper and a slam poet form an unlikely open-mic partnership that reignites both careers.', 'en'),
    (1016, "The Cartographer's Daughter", '2020-11-13', 7.5, 3700, 560.0, None, '', None, '', '12,14', '', "A mapmaker's daughter inherits an atlas of places that only exist while you're looking at the page.", 'en'),
    (1017, 'Dead Reckoning Bay', '2019-06-21', 6.8, 4400, 530.0, None, '', None, '', '9648,53', '', 'A harbor investigator reopens a decades-old disappearance after the same boat washes ashore again.', 'en'),
    (1018, 'Two-Lane Static', '2024-09-05', 7.1, 2100, 720.0, None, '', None, '', '18,10749', '', 'A long-haul trucker and a hitchhiking musician spend one cross-country night talking each other out of quitting.', 'en'),
    (1019, 'The Last Ember', '2015-01-30', 8.5, 8900, 470.0, None, '', None, '', '12,14,10751', '', "A blacksmith's apprentice sets out to relight the village forge using an ember said to be extinct.", 'en'),
    (1020, 'Nightshift Protocol', '2022-07-08', 7.0, 5600, 650.0, None, '', None, '', '878,53', '', "A hospital's new AI triage system starts making decisions no one authorized — and it's usually right.", 'en'),
    (1021, 'Confetti', '2018-02-09', 6.5, 2400, 440.0, None, '', None, '', '35,10751', '', 'A disastrous family wedding becomes the one weekend that actually brings everyone back together.', 'en'),
    (1022, 'The Frostline', '2023-03-24', 7.9, 4800, 690.0, None, '', None, '', '12,18', '', 'Two estranged climbing partners reunite for one final ascent neither of them can do alone.', 'en'),
    (1023, 'Static Bloom', '2017-08-18', 6.9, 3000, 460.0, None, '', None, '', '878,10749', '', "In a world where memories can be traded, a florist starts selling hers to pay for someone else's.", 'en'),
    (1024, 'The Understory', '2021-05-14', 8.3, 3900, 600.0, None, '', None, '', '99,18', '', 'A forester spends a year documenting an old-growth stand slated for clearing, and what she finds changes the plan.', 'en'),
    (1025, 'Backlot', '2020-10-02', 7.4, 2700, 510.0, None, '', None, '', '35,10402', '', "A struggling film crew keeps their production alive by secretly shooting a musical on someone else's set.", 'en'),
    (1026, 'The Signal Fire', '2024-06-27', 8.0, 3500, 830.0, None, '', None, '', '12,10752,18', '', "Villagers on a remote coast keep a centuries-old beacon lit, unaware of what it's actually warning off.", 'en'),
    (1027, 'Hush Harbor', '2019-11-29', 7.2, 4600, 550.0, None, '', None, '', '27,9648,53', '', "A lighthouse keeper's replacement finds the logbooks stop mid-sentence, three years ago, mid-storm.", 'en'),
    (1028, 'Roadside Attractions', '2016-09-16', 7.6, 6100, 500.0, None, '', None, '', '35,18', '', "A failing carnival's last season on the road becomes the thing that finally pulls its owner's family back together.", 'en'),
    (579974, 'RRR', '2022-03-24', 8.0, 1650, 78.5, '/tjpiEnZBUAA8pdNPRKa5vP2Zpqw.jpg', 'https://image.tmdb.org/t/p/w500/tjpiEnZBUAA8pdNPRKa5vP2Zpqw.jpg', '/i0Y0wP8H6SRgjr6QmuwbtQbS24D.jpg', 'https://image.tmdb.org/t/p/w1280/i0Y0wP8H6SRgjr6QmuwbtQbS24D.jpg', '28,12,18', 'revolution, friendship, pre-independence, fight, loyalty, rebel, british raj', "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.", 'te'),
    (20453, '3 Idiots', '2009-12-23', 8.0, 2400, 64.2, '/gmSRHU1Wtiatj8KoyVt8rT9ockx.jpg', 'https://image.tmdb.org/t/p/w500/gmSRHU1Wtiatj8KoyVt8rT9ockx.jpg', '/u7kuUaySqXBVAtqEl9vkTkAzHV9.jpg', 'https://image.tmdb.org/t/p/w1280/u7kuUaySqXBVAtqEl9vkTkAzHV9.jpg', '35,18', 'engineering, college life, friendship, pressure, student, innovation, mentor', "Rascal. Joker. Dreamer. Genius... You've never met a college student quite like &quot;Rancho.&quot; From the moment he arrives at India's most prestigious university, Rancho's outlandish schemes turn the campus upside down—along with the lives of his two newfound best friends. Together, they make life miserable for &quot;Virus,&quot; the school’s uptight and heartless dean. But when Rancho catches the eye of the dean's daughter, Virus sets his sights on flunking out the &quot;3 idiots&quot; once and for all.", 'hi'),
    (360814, 'Dangal', '2016-12-21', 8.0, 1850, 58.7, '/cJRPOLEexI7qp2DKtFfCh7YaaUG.jpg', 'https://image.tmdb.org/t/p/w500/cJRPOLEexI7qp2DKtFfCh7YaaUG.jpg', '/l0fNAHLOFReQJsxCOmGWvJDnimn.jpg', 'https://image.tmdb.org/t/p/w1280/l0fNAHLOFReQJsxCOmGWvJDnimn.jpg', '18,10751', 'wrestling, father daughter, sports, dedication, commonwealth games, female empowerment', 'Dangal is an extraordinary true story based on the life of Mahavir Singh and his two daughters, Geeta and Babita Phogat. The film traces the inspirational journey of a father who trains his daughters to become world class wrestlers.', 'hi'),
    (256040, 'Baahubali: The Beginning', '2015-07-10', 7.6, 1400, 62.4, '/9BAjt8nSSms62uOVYn1t3C3dVto.jpg', 'https://image.tmdb.org/t/p/w500/9BAjt8nSSms62uOVYn1t3C3dVto.jpg', '/e9ZEuHGHZ06AToHlfN1L7nejJ7W.jpg', 'https://image.tmdb.org/t/p/w1280/e9ZEuHGHZ06AToHlfN1L7nejJ7W.jpg', '28,12,14', 'kingdom, warrior, waterfall, destiny, royalty, mahishmati, epic battle', 'The young Shivudu is left as a foundling in a small village by his mother. By the time he’s grown up, it has become apparent that he possesses exceptional gifts. He meets the beautiful warrior princess Avanthika and learns that her queen has been held captive for the last 25 years. Shividu sets off to rescue her, discovering his own origins in the process.', 'te'),
    (350312, 'Baahubali 2: The Conclusion', '2017-04-27', 7.5, 1250, 65.1, '/sXf30F2HFpsFPXlNz7jpOySSV9I.jpg', 'https://image.tmdb.org/t/p/w500/sXf30F2HFpsFPXlNz7jpOySSV9I.jpg', '/whNjsTOUVg2lZLCKgGhnACnmV8E.jpg', 'https://image.tmdb.org/t/p/w1280/whNjsTOUVg2lZLCKgGhnACnmV8E.jpg', '28,12,14', 'dynasty, kingdom, betrayal, revenge, mahishmati, coronation, epic battle', 'When Mahendra, the son of Bāhubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.', 'te'),
    (568332, 'K.G.F: Chapter 1', '2018-12-20', 7.4, 950, 54.3, '/u6oXUTtOuJRPdUgUuPAVVJPSKCo.jpg', 'https://image.tmdb.org/t/p/w500/u6oXUTtOuJRPdUgUuPAVVJPSKCo.jpg', '/4uMrZS7XEHRNKwHr5wSOxROanPF.jpg', 'https://image.tmdb.org/t/p/w1280/4uMrZS7XEHRNKwHr5wSOxROanPF.jpg', '28,80,18', 'gold mines, underworld, gangster, rise to power, mother promise, rocky bhai', 'Taylor Swift takes the stage in Dallas for the Reputation Stadium Tour and celebrates a monumental night of music, memories and visual magic.', 'kn'),
    (587412, 'K.G.F: Chapter 2', '2022-04-13', 7.3, 850, 59.8, '/khNVygolU0TxLIDWff5tQlAhZ23.jpg', 'https://image.tmdb.org/t/p/w500/khNVygolU0TxLIDWff5tQlAhZ23.jpg', '/6q8r9m1x2y3u4v5.jpg', 'https://image.tmdb.org/t/p/w1280/6q8r9m1x2y3u4v5.jpg', '28,80,53', 'gold mines, kingpin, vengeance, prime minister, rebellion, empire, rocky', 'The blood-soaked land of Kolar Gold Fields (KGF) has a new overlord now - Rocky, whose name strikes fear in the heart of his foes. His allies look up to Rocky as their Savior, the government sees him as a threat to law and order; enemies are clamoring for revenge and conspiring for his downfall.', 'kn'),
    (12259, 'Sholay', '1975-08-15', 7.6, 680, 42.0, '/ya9bwgqA4eNl5bQ9QqS0jcmRoBS.jpg', 'https://image.tmdb.org/t/p/w500/ya9bwgqA4eNl5bQ9QqS0jcmRoBS.jpg', '/8r9m1x2y3u4v5w6.jpg', 'https://image.tmdb.org/t/p/w1280/8r9m1x2y3u4v5w6.jpg', '28,12,18', 'classic, dacoit, gabbar singh, revenge, friendship, jai veeru, ramgarh', 'After his family is murdered by a notorious and ruthless bandit of the ravines, a former police officer enlists the services of two outlaws to take down the bandit.', 'hi'),
    (1966, 'Lagaan: Once Upon a Time in India', '2001-06-15', 7.8, 820, 45.6, '/jrwQu72sGwGqwE8Ijne89PSIvhp.jpg', 'https://image.tmdb.org/t/p/w500/jrwQu72sGwGqwE8Ijne89PSIvhp.jpg', '/h21dxRjtR7xOhyZljtSYeTETCht.jpg', 'https://image.tmdb.org/t/p/w1280/h21dxRjtR7xOhyZljtSYeTETCht.jpg', '18,36', 'cricket, drought, british rule, villagers, tax, challenge, unity, patriotism', 'Alexander, the King of Macedonia, leads his legions against the giant Persian Empire. After defeating the Persians, he leads his army across the then known world, venturing farther than any westerner had ever gone, all the way to India.', 'hi'),
    (19404, 'Dilwale Dulhania Le Jayenge', '1995-10-20', 8.5, 4400, 89.2, '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg', 'https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg', '/84beTJf26mfhoasUlKSOiNSutyS.jpg', 'https://image.tmdb.org/t/p/w1280/84beTJf26mfhoasUlKSOiNSutyS.jpg', '35,18,10749', 'romance, europe trip, traditional family, marriage, simran, raj, punjab', 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'hi'),
    (297222, 'PK', '2014-12-18', 7.6, 1200, 52.8, '/i9V1uuUzJFPjdXOg6knfHci8Mha.jpg', 'https://image.tmdb.org/t/p/w500/i9V1uuUzJFPjdXOg6knfHci8Mha.jpg', '/gxfvtq5eYiClS2X7hxAAPBNrbWA.jpg', 'https://image.tmdb.org/t/p/w1280/gxfvtq5eYiClS2X7hxAAPBNrbWA.jpg', '35,18,878', 'alien, satire, religion, godman, broadcaster, remote control, innocence', "A stranger in the city asks questions no one has asked before. Known only by his initials, the man's innocent questions and childlike curiosity take him on a journey of love, laughter and letting go.", 'hi'),
    (872906, 'Jawan', '2023-09-07', 7.2, 550, 61.2, '/jFt1gS4BGHlK8xt76Y81Alp4dbt.jpg', 'https://image.tmdb.org/t/p/w500/jFt1gS4BGHlK8xt76Y81Alp4dbt.jpg', '/5LtSjMNw6j3LkG29Oa4O0iY5U8.jpg', 'https://image.tmdb.org/t/p/w1280/5LtSjMNw6j3LkG29Oa4O0iY5U8.jpg', '28,53', 'vigilante, social justice, father son, prison, corruption, soldier, double role', 'एक ऐसे व्यक्ति की भावनात्मक यात्रा जो वर्षों पहले किए गए वादे को निभाते हुए व्यक्तिगत प्रतिशोध से प्रेरित होकर, अपने अतीत से उबरने की कोशिश में, समाज में गलतियों को सुधारने के लिए तैयार है। एक हाई-ऑक्टेन एक्शन थ्रिलर जहां उसका मुकाबला एक भयानक राक्षसी डाकू से है जिसे कोई डर नहीं है और जिसने कई लोगों को अत्यधिक पीड़ा पहुंचाई है। यात्रा में उसकी मुलाकात एक उच्च विचारधारा वाली अनुभवी महिला अधिकारी से होगी, जिसकी भावनाएं इस लड़ाई में शामिल होने पर उस पर हावी हो सकती हैं। जैसे-जैसे उसका अतीत उससे आगे बढ़ता है, चुनौतियों पर काबू पाने और उनकी दुनिया में सद्भाव बहाल करने के लिए, उसे ऐसा करने के लिए सभी मारक क्षमता और बुद्धिमत्ता की आवश्यकता होगी।', 'hi'),
    (864692, 'Pathaan', '2023-01-25', 6.6, 620, 57.4, '/arf00BkwvXo0CFKbaD9OpqdE4Nu.jpg', 'https://image.tmdb.org/t/p/w500/arf00BkwvXo0CFKbaD9OpqdE4Nu.jpg', '/9wRAIQeOv2qzcgpfvA4dYZKeezl.jpg', 'https://image.tmdb.org/t/p/w1280/9wRAIQeOv2qzcgpfvA4dYZKeezl.jpg', '28,53,12', 'spy, raw agent, outfit x, missile, heist, patriotic, action chase', 'डायस्टोपियन मध्य पूर्व में कहीं, भव्य घर जो कभी अमीरों के घर थे, अब शहर के सबसे खतरनाक अपराधियों के घर हैं। एक अंडरकवर पुलिस वाला, उसका पूर्व-चुनाव, और अन्य लोग ड्रग लॉर्ड को नीचे उतारेंगे जिसने अपने ही पिता को मार डाला।', 'hi'),
    (15774, 'Swades', '2004-12-17', 8.1, 750, 44.1, '/yUSL24kpHc9Nls4Pohia4shgcIM.jpg', 'https://image.tmdb.org/t/p/w500/yUSL24kpHc9Nls4Pohia4shgcIM.jpg', '/4v5w6x7y8z9a0b1.jpg', 'https://image.tmdb.org/t/p/w1280/4v5w6x7y8z9a0b1.jpg', '18', 'nasa, nri, village, electricity, rural development, motherland, water power', 'A successful Indian scientist at NASA returns to an Indian village to take his childhood nanny to America with him and in the process rediscovers his roots.', 'hi'),
    (7508, 'Taare Zameen Par', '2007-12-21', 8.0, 1100, 49.3, '/lmz3fQV9wrrYiTU1gCdjhAc8pZ6.jpg', 'https://image.tmdb.org/t/p/w500/lmz3fQV9wrrYiTU1gCdjhAc8pZ6.jpg', '/bPwdy3zaNnMdZ22u0WCcYu0xxgt.jpg', 'https://image.tmdb.org/t/p/w1280/bPwdy3zaNnMdZ22u0WCcYu0xxgt.jpg', '18,10751', 'dyslexia, teacher, child, art, empathy, boarding school, special child', 'सपनों की दुनिया में रहने वाले ईशान को हॉस्टल भेज दिया जाता है, जहां लीक से हट कर सोचने वाला एक टीचर उसकी कल्पना को उड़ान भरने के लिए नए पंख देता है.', 'hi'),
    (781732, 'Vikram', '2022-06-03', 7.7, 480, 53.6, '/hr9rjR3J0xBBKmlJ4n3gHId9ccx.jpg', 'https://image.tmdb.org/t/p/w500/hr9rjR3J0xBBKmlJ4n3gHId9ccx.jpg', '/lprsAHkwMxk2iC6VZxNmV0H7g1t.jpg', 'https://image.tmdb.org/t/p/w1280/lprsAHkwMxk2iC6VZxNmV0H7g1t.jpg', '28,53,80', 'black squad, drugs syndicate, rolex, undercover, lcu, mask, retribution', 'एक धनी और शक्तिशाली उद्योगपति का बेटा भारत लौटता है और अपने पिता के जीवन को खतरे में डालने वालों के खिलाफ बदला लेने की चाहत में डूब जाता है, जिसके परिणामस्वरूप उसमें एक उल्लेखनीय परिवर्तन आता है।', 'ta'),
    (1024535, 'Kantara', '2022-09-30', 7.8, 520, 51.9, '/eyr8okTqsFTUVW3DD1edTMsWc3u.jpg', 'https://image.tmdb.org/t/p/w500/eyr8okTqsFTUVW3DD1edTMsWc3u.jpg', '/7R1gR2t4JL6raEOuZvbP3y0yl8r.jpg', 'https://image.tmdb.org/t/p/w1280/7R1gR2t4JL6raEOuZvbP3y0yl8r.jpg', '28,12,53', 'demigod, forest land, bhoota kola, tribal rights, folklore, daiva, divine trance', 'Afflicted with a mysterious disease after surviving an overdose, a woman returns to her childhood home to confront her personal demons but instead discovers a real one.', 'kn'),
    (185008, 'Yeh Jawaani Hai Deewani', '2013-05-31', 7.3, 690, 48.7, '/em39H81XLCDgXsI7V4IcBZseEO6.jpg', 'https://image.tmdb.org/t/p/w500/em39H81XLCDgXsI7V4IcBZseEO6.jpg', '/hvaSiRRM93aCSzTmKlY4sHERL0S.jpg', 'https://image.tmdb.org/t/p/w1280/hvaSiRRM93aCSzTmKlY4sHERL0S.jpg', '10749,35,18', 'trekking, manali, wedding, dreams, career, friends, travel, love', 'On a trekking trip, an introverted Naina falls for a charming ex-classmate, whose thirst for adventure drives them apart. Years later, their paths cross again.', 'hi'),
    (7913, 'Rang De Basanti', '2006-01-26', 7.9, 780, 46.2, '/f1bF8CHzEu621bPSIg6XiUNAabh.jpg', 'https://image.tmdb.org/t/p/w500/f1bF8CHzEu621bPSIg6XiUNAabh.jpg', '/fgRhyGbMAolDsQ65VRBRBtVQZNn.jpg', 'https://image.tmdb.org/t/p/w1280/fgRhyGbMAolDsQ65VRBRBtVQZNn.jpg', '18,36', 'freedom fighters, documentary, youth, corruption, air force, patriotism, awakening', 'ब्रिटिश राज के खिलाफ़ भारत में 1920 की क्रांति पर अंग्रेज़ फ़िल्मकार डॉक्यूड्रामा बना रही है. इसमें काम करते करते छात्र एक्टरों का जीवन के प्रति नज़रिया ही बदल जाता है.', 'hi'),
    (4251, 'Veer-Zaara', '2004-11-12', 7.8, 610, 47.9, '/r9MFHgWwVKYXksjgPCmtyEEiLSc.jpg', 'https://image.tmdb.org/t/p/w500/r9MFHgWwVKYXksjgPCmtyEEiLSc.jpg', '/tID8mHaMGDwh9sNydvSo3U1fdxb.jpg', 'https://image.tmdb.org/t/p/w1280/tID8mHaMGDwh9sNydvSo3U1fdxb.jpg', '18,10749', 'india pakistan, cross-border romance, lawyer, prison, sacrifice, punjab, unconditional love', 'Squadron Leader Veer Pratap Singh, a pilot in the Indian Air Force, rescues the stranded Zaara, a woman from Pakistan, following a bus accident, and their lives are forever bound.', 'hi'),
]

def _row(id_, title, date, rating, votes, pop, poster_path, poster_url, backdrop_path, backdrop_url, genres, keywords, overview, language="en"):
    return {
        "id": id_, "title": title, "original_title": title, "overview": overview,
        "release_date": date, "vote_average": rating, "vote_count": votes, "popularity": pop,
        "poster_path": poster_path, "poster_url": poster_url,
        "backdrop_path": backdrop_path, "backdrop_url": backdrop_url,
        "genres": genres, "keywords": keywords, "language": language, "adult": False,
    }

MOVIES = [_row(*r) for r in _RAW]
